package com.leo.domain;
// Generated 2017-3-8 21:40:43 by Hibernate Tools 4.0.1.Final

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int id;
	private String username;
	private Double salary;

	public Account() {
	}

	public Account(int id) {
		this.id = id;
	}

	public Account(int id, String username, Double salary) {
		this.id = id;
		this.username = username;
		this.salary = salary;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

}
